apiVersion: v1
kind: Service
namespace: default
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
